import os

class Config(object):
  SECRET_KEY = os.environ.get('SECRET_KEY') or 'key-for-devs'
  SQLALCHEMY_TRACK_MODIFICATIONS = False
  SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
  AZURE_STORAGE_ACCOUNT_NAME = os.environ.get("AZURE_STORAGE_ACCOUNT_NAME")
  AZURE_STORAGE_ACCOUNT_KEY = os.environ.get("AZURE_STORAGE_ACCOUNT_KEY")
  AZURE_CONTAINER_NAME = os.environ.get("AZURE_CONTAINER_NAME")